//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONHANG
    {
        public decimal MASP { get; set; }
        public decimal MADH { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> GIASP { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual DONHANG DONHANG { get; set; }
    }
}
