//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public decimal MASP { get; set; }
        public decimal MAHD { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> GIA { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
