//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDTTHOPDONG
    {
        public decimal MAHDTTHOPDONG { get; set; }
        public string MAHOPDONG { get; set; }
        public decimal MAHTTT { get; set; }
        public Nullable<decimal> SOTIENCOC { get; set; }
        public Nullable<decimal> SOTIENCONLAI { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual HINHTHUCTT HINHTHUCTT { get; set; }
    }
}
