//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public decimal MAHD { get; set; }
        public decimal MADH { get; set; }
        public Nullable<System.DateTime> NGAYLAPHD { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
