//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHOADON = new HashSet<CHITIETHOADON>();
        }
    
        public decimal MAHD { get; set; }
        public Nullable<System.DateTime> THOIGIANDAT { get; set; }
        public Nullable<System.DateTime> THOIGIANGIAODUKIEN { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public string DIACHI { get; set; }
        public string SDTNHAN { get; set; }
        public string TENDANGNHAP { get; set; }
        public decimal MAHTTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADON { get; set; }
        public virtual HINHTHUCTT HINHTHUCTT { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
