//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOPDONG
    {
        public string MAHOPDONG { get; set; }
        public Nullable<System.DateTime> THOIGIANLAP { get; set; }
        public string ND { get; set; }
        public string CHIPHIDULOAISP { get; set; }
        public string TENDANGNHAP { get; set; }
        public string TENTAIKHOAN { get; set; }
        public decimal MALOAIHD { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual LOAIHD LOAIHD { get; set; }
    }
}
