//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOPDONG = new HashSet<HOPDONG>();
        }
    
        public string TENTAIKHOAN { get; set; }
        public string PASS { get; set; }
        public string TENNHANVIEN { get; set; }
        public Nullable<System.DateTime> NS { get; set; }
        public string SODT { get; set; }
        public string DIACHI { get; set; }
        public string MAIL { get; set; }
        public decimal MAQH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOPDONG> HOPDONG { get; set; }
        public virtual QUYENHAN QUYENHAN { get; set; }
    }
}
